### ISSUE TITLE
using OLED via I2C on the ESP-12

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [somhi/ESP_SSD1306#2]
Did this library also work for I2C connection?
I can not bring the display to life.
OLED display:
- I2C (VCC, GND, SCL, SDA)
- 128x64

please help.
I have already the RC522 RFID module connected to SPI and there are only 3 GPIOs left -so I need I2C

**Comment by somhi** [comment]
I have not tried for myself, but a I know someone who tried it and works.  His code is:
include libraries ESP_SSD1306.h,Adafruit_GFX.h,SPI.h,Wire.h

#define OLED_RESET  5  // Pin 11 -RESET digital signal
ESP_SSD1306 display(OLED_RESET); //I2C constructor

void setup(void)
{ 
  Wire.pins(13, 14); // (sda,scl) choose your pins here
  display.begin(SSD1306_SWITCHCAPVCC, 0x3C, false);   //  his displays says 0x78 but is working with 0x3C

}

**Comment by Jorgen-VikingGod** [comment]
Sorry - I found the bug.
It was an issue with my cabling :/
Sorry for that - the voltage was too low for, so the IO pins did not get enough power to drive the display.
I was using the ESP8266 test board with battery pack. Now with power supply of 5 V (down to 3.3V) everything works perfect.

> closed
