### ISSUE TITLE
The little modification of Adafruit_GFX.cpp might not be necessary anymore

### ISSUE THREAD

**Issue by maitai** [somhi/ESP_SSD1306#4]
It looks like the differentiation between AVR and ESP8266 is now already incorporated into the Adafruit-GFX-Library:

https://github.com/adafruit/Adafruit-GFX-Library/blob/93dde8b70a6468b44e9ab25af9fca71098f380ec/Adafruit_GFX.cpp#L36-L46

**Comment by maitai** [comment]
adafruit/Adafruit-GFX-Library#48

**Comment by somhi** [comment]
Thanks for letting me know.
